# Development environment configuration
# Override settings for development deployment

targets:
  dev:
    # Development-specific pipeline settings
    mode: development
    default: true
    workspace:
      host: https://adb-1585634049715221.1.azuredatabricks.net/
    
    resources:
      pipelines:
        fred_dlt_pipeline:
          # Use triggered mode in dev for cost savings
          continuous: false

          # Development cluster configuration
          serverless: true

          # Lenient data quality in dev for testing
          expectations:
            fail_on_error: false

          # No notifications in dev
          # notifications: []

          # Development table properties
          configuration:
            catalog: ${var.catalog}
            schema: ${var.schema}
