# Production environment configuration
# Override settings for production deployment

targets:
  prod:
    # Production-specific pipeline settings
    mode: production
    workspace:
      host: ${var.prod_host}

    resources:
      pipelines:
        fred_dlt_pipeline:
          # Use continuous mode in production for real-time processing
          continuous: true

          # Production cluster configuration
          serverless: true

          # Stricter data quality in production
          expectations:
            fail_on_error: true

          # Enable notifications for production failures
          notifications:
            - alerts:
                - "on-update-failure"
                - "on-flow-failure"
              email_recipients:
                - ${var.email_rec}

          # Production table properties
          configuration:
            catalog: ${var.catalog}
            schema: ${var.schema}
            # Add production-specific configs
            pipelines.reset.allowed: "false"
